services:
  main:
    image: docker.io/yugabytedb/yugabyte:latest
    entrypoint: |
      bash -c '
      bin/yugabyted start --daemon=false
      '
    ports:
      - 7000:7000
      - 9000:9000
      - 5433:5433
      - 9042:9042
      - 15433:15433
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=password
