services:
  yb-master-n1:
    image: docker.io/yugabytedb/yugabyte:2.19.2.0-b121
    entrypoint: |
      bash -c '
        /home/yugabyte/bin/yb-master --replication_factor=3 --master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 \
        --rpc_bind_addresses=yb-master-n1:7100 --fs_data_dirs=/home/yugabyte/base_dir \
        --ysql_num_shards_per_tserver=2
      '
    ports:
      - 7000:7000
    volumes:
      - ../.yugabyte_data/yb-master-n1:/home/yugabyte/base_dir

  yb-master-n2:
    image: docker.io/yugabytedb/yugabyte:2.19.2.0-b121
    entrypoint: |
      bash -c '
        /home/yugabyte/bin/yb-master --replication_factor=3 --master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 \
        --rpc_bind_addresses=yb-master-n2:7100 --fs_data_dirs=/home/yugabyte/base_dir \
        --ysql_num_shards_per_tserver=2
      '
    volumes:
      - ../.yugabyte_data/yb-master-n2:/home/yugabyte/base_dir

  yb-master-n3:
    image: docker.io/yugabytedb/yugabyte:2.19.2.0-b121
    entrypoint: |
      bash -c '
        /home/yugabyte/bin/yb-master --replication_factor=3 --master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 \
        --rpc_bind_addresses=yb-master-n3:7100 --fs_data_dirs=/home/yugabyte/base_dir \
        --ysql_num_shards_per_tserver=2
      '
    volumes:
      - ../.yugabyte_data/yb-master-n3:/home/yugabyte/base_dir

  yb-tserver-n1:
    image: docker.io/yugabytedb/yugabyte:2.19.2.0-b121
    entrypoint: |
      bash -c '
        /home/yugabyte/bin/yb-tserver --tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 \
        --rpc_bind_addresses=yb-tserver-n1:9100 --memory_limit_hard_bytes=1073741824 \
        --pgsql_proxy_bind_address yb-tserver-n1:5433 \
        --fs_data_dirs=/home/yugabyte/base_dir --ysql_num_shards_per_tserver=2
      '
    ports:
      - 9000:9000
      - 9042:9042
      - 6379:6379
      - 5433:5433
    volumes:
      - ../.yugabyte_data/yb-tserver-n1:/home/yugabyte/base_dir

  yb-tserver-n2:
    image: docker.io/yugabytedb/yugabyte:2.19.2.0-b121
    entrypoint: |
      bash -c '
        /home/yugabyte/bin/yb-tserver --tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 \
        --rpc_bind_addresses=yb-tserver-n2:9100 --memory_limit_hard_bytes=1073741824 \
        --pgsql_proxy_bind_address yb-tserver-n2:5433 \
        --fs_data_dirs=/home/yugabyte/base_dir --ysql_num_shards_per_tserver=2
      '
    volumes:
      - ../.yugabyte_data/yb-tserver-n2:/home/yugabyte/base_dir

  yb-tserver-n3:
    image: docker.io/yugabytedb/yugabyte:2.19.2.0-b121
    entrypoint: |
      bash -c '
        /home/yugabyte/bin/yb-tserver --tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100 \
        --rpc_bind_addresses=yb-tserver-n3:9100 --memory_limit_hard_bytes=1073741824 \
        --pgsql_proxy_bind_address yb-tserver-n3:5433 \
        --fs_data_dirs=/home/yugabyte/base_dir --ysql_num_shards_per_tserver=2
      '
    volumes:
      - ../.yugabyte_data/yb-tserver-n3:/home/yugabyte/base_dir

